export interface CollegePlacement {
  slug: string;
  name: string;
  shortName: string;
  location: string;
  type: 'IIT' | 'NIT' | 'IIIT' | 'Private' | 'State' | 'Deemed';
  ranking: number; // NIRF rank
  stats: {
    year: string;
    placementRate: string;
    avgCTC: number;
    medianCTC: number;
    maxCTC: number;
    studentsPlaced: number;
    companiesVisited: number;
  }[];
  topRecruiters: string[];
  branchWise: { branch: string; avgCTC: number; placementRate: string }[];
  highlights: string[];
}

export const colleges: CollegePlacement[] = [
  {
    slug: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    location: 'Mumbai, Maharashtra',
    type: 'IIT',
    ranking: 3,
    stats: [
      {
        year: '2025',
        placementRate: '95%',
        avgCTC: 26.5,
        medianCTC: 21,
        maxCTC: 310,
        studentsPlaced: 1350,
        companiesVisited: 380,
      },
      {
        year: '2024',
        placementRate: '93%',
        avgCTC: 24.8,
        medianCTC: 20,
        maxCTC: 280,
        studentsPlaced: 1280,
        companiesVisited: 350,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Goldman Sachs',
      'Uber',
      'Amazon',
      'JP Morgan',
      'Tower Research',
      'DE Shaw',
      'Samsung',
      'Qualcomm',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 45, placementRate: '100%' },
      { branch: 'Electrical', avgCTC: 22, placementRate: '95%' },
      { branch: 'Mechanical', avgCTC: 18, placementRate: '88%' },
      { branch: 'Chemical', avgCTC: 16, placementRate: '82%' },
    ],
    highlights: [
      'Highest number of PPOs in India',
      'Strong quant/finance placements',
      'Research internships at MIT, Stanford',
    ],
  },
  {
    slug: 'iit-delhi',
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    location: 'New Delhi',
    type: 'IIT',
    ranking: 2,
    stats: [
      {
        year: '2025',
        placementRate: '94%',
        avgCTC: 25.8,
        medianCTC: 20,
        maxCTC: 280,
        studentsPlaced: 1200,
        companiesVisited: 360,
      },
      {
        year: '2024',
        placementRate: '92%',
        avgCTC: 24,
        medianCTC: 19,
        maxCTC: 250,
        studentsPlaced: 1150,
        companiesVisited: 340,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Amazon',
      'Goldman Sachs',
      'McKinsey',
      'BCG',
      'Samsung',
      'Adobe',
      'Flipkart',
      'Uber',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 42, placementRate: '100%' },
      { branch: 'Electrical', avgCTC: 21, placementRate: '94%' },
      { branch: 'Mechanical', avgCTC: 17, placementRate: '86%' },
      { branch: 'Civil', avgCTC: 14, placementRate: '78%' },
    ],
    highlights: [
      'Strong consulting placements (McKinsey, BCG)',
      'Startup ecosystem',
      'Industry-sponsored research labs',
    ],
  },
  {
    slug: 'iit-madras',
    name: 'Indian Institute of Technology Madras',
    shortName: 'IIT Madras',
    location: 'Chennai, Tamil Nadu',
    type: 'IIT',
    ranking: 1,
    stats: [
      {
        year: '2025',
        placementRate: '96%',
        avgCTC: 24.5,
        medianCTC: 19.5,
        maxCTC: 210,
        studentsPlaced: 1300,
        companiesVisited: 370,
      },
      {
        year: '2024',
        placementRate: '94%',
        avgCTC: 22.8,
        medianCTC: 18,
        maxCTC: 190,
        studentsPlaced: 1250,
        companiesVisited: 350,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Amazon',
      'Samsung',
      'Texas Instruments',
      'Intel',
      'Qualcomm',
      'Goldman Sachs',
      'DE Shaw',
      'Sprinklr',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 40, placementRate: '100%' },
      { branch: 'Electrical', avgCTC: 20, placementRate: '96%' },
      { branch: 'Mechanical', avgCTC: 16, placementRate: '90%' },
      { branch: 'Aerospace', avgCTC: 15, placementRate: '85%' },
    ],
    highlights: [
      'NIRF #1 ranked for 6 consecutive years',
      'Strong core engineering placements',
      'IIT Madras Research Park ecosystem',
    ],
  },
  {
    slug: 'iit-kanpur',
    name: 'Indian Institute of Technology Kanpur',
    shortName: 'IIT Kanpur',
    location: 'Kanpur, UP',
    type: 'IIT',
    ranking: 4,
    stats: [
      {
        year: '2025',
        placementRate: '90%',
        avgCTC: 23.5,
        medianCTC: 18,
        maxCTC: 250,
        studentsPlaced: 1100,
        companiesVisited: 320,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Samsung',
      'Goldman Sachs',
      'Uber',
      'Tower Research',
      'DE Shaw',
      'Adobe',
      'Flipkart',
      'Intel',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 38, placementRate: '100%' },
      { branch: 'Electrical', avgCTC: 20, placementRate: '92%' },
      { branch: 'Mechanical', avgCTC: 16, placementRate: '84%' },
    ],
    highlights: [
      'Entrepreneurship Cell (E-Cell) is one of the oldest in India',
      'Strong competitive programming culture',
    ],
  },
  {
    slug: 'iit-kharagpur',
    name: 'Indian Institute of Technology Kharagpur',
    shortName: 'IIT Kharagpur',
    location: 'Kharagpur, West Bengal',
    type: 'IIT',
    ranking: 6,
    stats: [
      {
        year: '2025',
        placementRate: '92%',
        avgCTC: 22,
        medianCTC: 17,
        maxCTC: 200,
        studentsPlaced: 1500,
        companiesVisited: 400,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Amazon',
      'Goldman Sachs',
      'Qualcomm',
      'Samsung',
      'Schlumberger',
      'EXL',
      'Shell',
      'TATA',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 35, placementRate: '100%' },
      { branch: 'Electrical', avgCTC: 19, placementRate: '94%' },
      { branch: 'Mining', avgCTC: 14, placementRate: '80%' },
    ],
    highlights: [
      'Largest IIT campus',
      'Highest number of students placed',
      'Strong in core and non-core sectors',
    ],
  },
  {
    slug: 'nit-trichy',
    name: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    type: 'NIT',
    ranking: 9,
    stats: [
      {
        year: '2025',
        placementRate: '94%',
        avgCTC: 14,
        medianCTC: 10,
        maxCTC: 60,
        studentsPlaced: 850,
        companiesVisited: 280,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Google',
      'Samsung',
      'TCS',
      'Infosys',
      'Oracle',
      'Cisco',
      'Caterpillar',
      'L&T',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 22, placementRate: '100%' },
      { branch: 'ECE', avgCTC: 12, placementRate: '95%' },
      { branch: 'Mechanical', avgCTC: 9, placementRate: '86%' },
    ],
    highlights: [
      'Best NIT in India',
      'Strong alumni network',
      'Pragyan — largest student-run tech fest',
    ],
  },
  {
    slug: 'nit-warangal',
    name: 'National Institute of Technology Warangal',
    shortName: 'NIT Warangal',
    location: 'Warangal, Telangana',
    type: 'NIT',
    ranking: 12,
    stats: [
      {
        year: '2025',
        placementRate: '92%',
        avgCTC: 13,
        medianCTC: 9.5,
        maxCTC: 52,
        studentsPlaced: 800,
        companiesVisited: 260,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Google',
      'TCS',
      'Infosys',
      'Wipro',
      'Samsung',
      'Oracle',
      'Cisco',
      'Deloitte',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 20, placementRate: '100%' },
      { branch: 'ECE', avgCTC: 11, placementRate: '93%' },
    ],
    highlights: [
      'Strong coding culture',
      'Good product company placements for a NIT',
    ],
  },
  {
    slug: 'nit-surathkal',
    name: 'National Institute of Technology Karnataka',
    shortName: 'NITK Surathkal',
    location: 'Surathkal, Karnataka',
    type: 'NIT',
    ranking: 10,
    stats: [
      {
        year: '2025',
        placementRate: '93%',
        avgCTC: 13.5,
        medianCTC: 10,
        maxCTC: 55,
        studentsPlaced: 830,
        companiesVisited: 270,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Samsung',
      'Cisco',
      'Oracle',
      'TCS',
      'Infosys',
      'Goldman Sachs',
      'Flipkart',
      'Adobe',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 21, placementRate: '100%' },
      { branch: 'ECE', avgCTC: 12, placementRate: '94%' },
    ],
    highlights: [
      'Beachside campus',
      'Strong product company presence',
      'Engineer — tech fest',
    ],
  },
  {
    slug: 'iiit-hyderabad',
    name: 'International Institute of Information Technology Hyderabad',
    shortName: 'IIIT Hyderabad',
    location: 'Hyderabad, Telangana',
    type: 'IIIT',
    ranking: 35,
    stats: [
      {
        year: '2025',
        placementRate: '98%',
        avgCTC: 25,
        medianCTC: 20,
        maxCTC: 130,
        studentsPlaced: 450,
        companiesVisited: 180,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Amazon',
      'Uber',
      'Adobe',
      'Flipkart',
      'Goldman Sachs',
      'Sprinklr',
      'De Shaw',
      'Salesforce',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 28, placementRate: '100%' },
      { branch: 'ECE', avgCTC: 18, placementRate: '95%' },
    ],
    highlights: [
      'Highest avg CTC among IIITs',
      'Research-focused curriculum',
      'Strong AI/ML placements',
    ],
  },
  {
    slug: 'bits-pilani',
    name: 'Birla Institute of Technology and Science, Pilani',
    shortName: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    type: 'Deemed',
    ranking: 13,
    stats: [
      {
        year: '2025',
        placementRate: '92%',
        avgCTC: 18,
        medianCTC: 14,
        maxCTC: 120,
        studentsPlaced: 1000,
        companiesVisited: 300,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Samsung',
      'Goldman Sachs',
      'Amazon',
      'Adobe',
      'Flipkart',
      'DE Shaw',
      'Uber',
      'Cisco',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 28, placementRate: '100%' },
      { branch: 'Electronics', avgCTC: 15, placementRate: '92%' },
    ],
    highlights: [
      'Practice School — mandatory industry internship',
      'Strong startup culture',
      'Dual degree unique to BITS',
    ],
  },
  {
    slug: 'vit-vellore',
    name: 'Vellore Institute of Technology',
    shortName: 'VIT Vellore',
    location: 'Vellore, Tamil Nadu',
    type: 'Private',
    ranking: 15,
    stats: [
      {
        year: '2025',
        placementRate: '90%',
        avgCTC: 8.5,
        medianCTC: 6.5,
        maxCTC: 65,
        studentsPlaced: 7000,
        companiesVisited: 700,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'TCS',
      'Infosys',
      'Wipro',
      'Cognizant',
      'Deloitte',
      'Accenture',
      'Samsung',
      'Capgemini',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 12, placementRate: '96%' },
      { branch: 'ECE', avgCTC: 7, placementRate: '88%' },
      { branch: 'Mechanical', avgCTC: 5.5, placementRate: '78%' },
    ],
    highlights: [
      'Highest number of students placed in India',
      'VTOP — online course system',
      'International exchange programs',
    ],
  },
  {
    slug: 'srm-chennai',
    name: 'SRM Institute of Science and Technology',
    shortName: 'SRM Chennai',
    location: 'Chennai, Tamil Nadu',
    type: 'Private',
    ranking: 25,
    stats: [
      {
        year: '2025',
        placementRate: '87%',
        avgCTC: 7.5,
        medianCTC: 5.5,
        maxCTC: 54,
        studentsPlaced: 6500,
        companiesVisited: 600,
      },
    ],
    topRecruiters: [
      'TCS',
      'Infosys',
      'Wipro',
      'Cognizant',
      'Accenture',
      'Amazon',
      'Samsung',
      'Deloitte',
      'Capgemini',
      'HCLTech',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 10, placementRate: '94%' },
      { branch: 'ECE', avgCTC: 6, placementRate: '84%' },
    ],
    highlights: [
      'Strong industry partnerships',
      'International campus in India',
    ],
  },
  {
    slug: 'dtu-delhi',
    name: 'Delhi Technological University',
    shortName: 'DTU',
    location: 'New Delhi',
    type: 'State',
    ranking: 20,
    stats: [
      {
        year: '2025',
        placementRate: '91%',
        avgCTC: 15,
        medianCTC: 11,
        maxCTC: 90,
        studentsPlaced: 1800,
        companiesVisited: 350,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Amazon',
      'Samsung',
      'Goldman Sachs',
      'Adobe',
      'Flipkart',
      'TCS',
      'Infosys',
      'Oracle',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 24, placementRate: '100%' },
      { branch: 'IT', avgCTC: 18, placementRate: '96%' },
      { branch: 'ECE', avgCTC: 12, placementRate: '88%' },
    ],
    highlights: [
      'Delhi location advantage',
      'Strong alumni in startups',
      'Formerly DCE — rich history',
    ],
  },
  {
    slug: 'nsut-delhi',
    name: 'Netaji Subhas University of Technology',
    shortName: 'NSUT',
    location: 'New Delhi',
    type: 'State',
    ranking: 23,
    stats: [
      {
        year: '2025',
        placementRate: '89%',
        avgCTC: 14,
        medianCTC: 10.5,
        maxCTC: 80,
        studentsPlaced: 1200,
        companiesVisited: 300,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Google',
      'Samsung',
      'Adobe',
      'Goldman Sachs',
      'Flipkart',
      'Oracle',
      'TCS',
      'Infosys',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 22, placementRate: '100%' },
      { branch: 'IT', avgCTC: 16, placementRate: '95%' },
    ],
    highlights: [
      'Formerly NSIT — strong brand in Delhi',
      'Good product company placements',
    ],
  },
  {
    slug: 'manipal-mit',
    name: 'Manipal Institute of Technology',
    shortName: 'MIT Manipal',
    location: 'Manipal, Karnataka',
    type: 'Private',
    ranking: 18,
    stats: [
      {
        year: '2025',
        placementRate: '85%',
        avgCTC: 9,
        medianCTC: 6.5,
        maxCTC: 50,
        studentsPlaced: 2500,
        companiesVisited: 400,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Samsung',
      'TCS',
      'Infosys',
      'Wipro',
      'Oracle',
      'Cisco',
      'VMware',
      'SAP',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 14, placementRate: '96%' },
      { branch: 'ECE', avgCTC: 8, placementRate: '84%' },
    ],
    highlights: [
      'Beautiful campus',
      'Strong alumni network globally',
      'Good international exposure',
    ],
  },
  {
    slug: 'iiit-bangalore',
    name: 'International Institute of Information Technology Bangalore',
    shortName: 'IIIT Bangalore',
    location: 'Bangalore, Karnataka',
    type: 'IIIT',
    ranking: 40,
    stats: [
      {
        year: '2025',
        placementRate: '97%',
        avgCTC: 22,
        medianCTC: 18,
        maxCTC: 100,
        studentsPlaced: 350,
        companiesVisited: 150,
      },
    ],
    topRecruiters: [
      'Google',
      'Microsoft',
      'Amazon',
      'Flipkart',
      'Adobe',
      'Samsung',
      'Goldman Sachs',
      'Uber',
      'Cisco',
      'Intel',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 24, placementRate: '100%' },
      { branch: 'ECE', avgCTC: 16, placementRate: '95%' },
    ],
    highlights: [
      'Bangalore tech-hub location',
      'Strong startup placements',
      'Industry-integrated curriculum',
    ],
  },
  {
    slug: 'nit-rourkela',
    name: 'National Institute of Technology Rourkela',
    shortName: 'NIT Rourkela',
    location: 'Rourkela, Odisha',
    type: 'NIT',
    ranking: 14,
    stats: [
      {
        year: '2025',
        placementRate: '88%',
        avgCTC: 11,
        medianCTC: 8,
        maxCTC: 45,
        studentsPlaced: 750,
        companiesVisited: 240,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Samsung',
      'TCS',
      'Infosys',
      'Oracle',
      'L&T',
      'JSW',
      'Tata Steel',
      'BPCL',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 18, placementRate: '100%' },
      { branch: 'Metallurgy', avgCTC: 10, placementRate: '90%' },
    ],
    highlights: ['Strong core placements (Steel, Mining)', 'NIRF top 15 NIT'],
  },
  {
    slug: 'thapar-patiala',
    name: 'Thapar Institute of Engineering and Technology',
    shortName: 'Thapar University',
    location: 'Patiala, Punjab',
    type: 'Deemed',
    ranking: 30,
    stats: [
      {
        year: '2025',
        placementRate: '85%',
        avgCTC: 9.5,
        medianCTC: 7,
        maxCTC: 50,
        studentsPlaced: 1100,
        companiesVisited: 280,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Samsung',
      'TCS',
      'Infosys',
      'Wipro',
      'Deloitte',
      'Goldman Sachs',
      'Flipkart',
      'Oracle',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 16, placementRate: '98%' },
      { branch: 'ECE', avgCTC: 8, placementRate: '86%' },
    ],
    highlights: [
      'Strong in Punjab region',
      'Good mix of product and service companies',
    ],
  },
  {
    slug: 'jadavpur-university',
    name: 'Jadavpur University',
    shortName: 'Jadavpur',
    location: 'Kolkata, West Bengal',
    type: 'State',
    ranking: 16,
    stats: [
      {
        year: '2025',
        placementRate: '82%',
        avgCTC: 10,
        medianCTC: 7.5,
        maxCTC: 60,
        studentsPlaced: 800,
        companiesVisited: 200,
      },
    ],
    topRecruiters: [
      'Google',
      'Amazon',
      'TCS',
      'Infosys',
      'Cognizant',
      'Samsung',
      'Oracle',
      'Wipro',
      'Capgemini',
      'L&T',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 16, placementRate: '96%' },
      { branch: 'IT', avgCTC: 12, placementRate: '90%' },
    ],
    highlights: [
      'Autonomous — no tuition fees for merit students',
      'Strong research output',
    ],
  },
  {
    slug: 'pec-chandigarh',
    name: 'Punjab Engineering College',
    shortName: 'PEC Chandigarh',
    location: 'Chandigarh',
    type: 'Deemed',
    ranking: 28,
    stats: [
      {
        year: '2025',
        placementRate: '86%',
        avgCTC: 11,
        medianCTC: 8,
        maxCTC: 55,
        studentsPlaced: 600,
        companiesVisited: 200,
      },
    ],
    topRecruiters: [
      'Microsoft',
      'Amazon',
      'Samsung',
      'TCS',
      'Infosys',
      'Oracle',
      'Adobe',
      'Flipkart',
      'Goldman Sachs',
      'Cisco',
    ],
    branchWise: [
      { branch: 'CSE', avgCTC: 18, placementRate: '98%' },
      { branch: 'ECE', avgCTC: 10, placementRate: '88%' },
    ],
    highlights: [
      'Government college — low fees',
      'Chandigarh location advantage',
      'Strong alumni network',
    ],
  },
];

export function getCollegeBySlug(slug: string): CollegePlacement | undefined {
  return colleges.find((c) => c.slug === slug);
}

export function getCollegeSlugs(): string[] {
  return colleges.map((c) => c.slug);
}

export function getCollegesByType(): Record<string, CollegePlacement[]> {
  return colleges.reduce(
    (acc, c) => {
      if (!acc[c.type]) acc[c.type] = [];
      acc[c.type].push(c);
      return acc;
    },
    {} as Record<string, CollegePlacement[]>,
  );
}

export const collegeTypeLabels: Record<string, string> = {
  IIT: '🏛️ Indian Institutes of Technology',
  NIT: '🎓 National Institutes of Technology',
  IIIT: '💻 IIITs',
  Private: '🏢 Top Private Universities',
  State: '📍 State Universities',
  Deemed: '⭐ Deemed Universities',
};
