// Centralized search index containing all searchable content
import { SearchItem } from '@/types/search-types';
import { blogPosts } from '@/lib/blog-data';

// Tools data
const tools: SearchItem[] = [
  {
    id: 'cgpa-converter',
    title: 'CGPA Converter',
    description: 'Convert CGPA to percentage and vice versa',
    category: 'tools',
    keywords: ['cgpa', 'percentage', 'grade', 'convert', 'gpa'],
    href: '/tools/cgpa-converter',
  },
  {
    id: 'resume-builder',
    title: 'Resume Builder',
    description: 'Create professional resumes with templates',
    category: 'tools',
    keywords: ['resume', 'cv', 'builder', 'template', 'job'],
    href: '/tools/resume-builder',
  },
  {
    id: 'resume-score-checker',
    title: 'Resume Score Checker',
    description: 'Check your resume score and get improvement tips',
    category: 'tools',
    keywords: ['resume', 'score', 'ats', 'check', 'improve'],
    href: '/tools/resume-score-checker',
  },
  {
    id: 'salary-calculator',
    title: 'Salary Calculator',
    description: 'Calculate your in-hand salary after deductions',
    category: 'tools',
    keywords: ['salary', 'tax', 'income', 'calculate', 'ctc'],
    href: '/tools/salary-calculator',
  },
  {
    id: 'emi-calculator',
    title: 'EMI Calculator',
    description: 'Calculate loan EMI, interest, and total amount',
    category: 'tools',
    keywords: ['emi', 'loan', 'interest', 'calculate', 'mortgage'],
    href: '/tools/emi-calculator',
  },
  {
    id: 'aptitude-test',
    title: 'Aptitude Test',
    description: 'Practice aptitude questions for placements',
    category: 'tools',
    keywords: ['aptitude', 'test', 'practice', 'placement', 'quantitative'],
    href: '/tools/aptitude-test',
  },
  {
    id: 'typing-test',
    title: 'Typing Test',
    description: 'Test and improve your typing speed',
    category: 'tools',
    keywords: ['typing', 'speed', 'test', 'wpm', 'practice'],
    href: '/tools/typing-test',
  },
  {
    id: 'cover-letter-generator',
    title: 'Cover Letter Generator',
    description: 'Generate professional cover letters quickly',
    category: 'tools',
    keywords: ['cover', 'letter', 'job', 'application', 'generate'],
    href: '/tools/cover-letter-generator',
  },
  {
    id: 'career-roadmap',
    title: 'Career Roadmap',
    description: 'Plan your career path with visual roadmaps',
    category: 'tools',
    keywords: ['career', 'roadmap', 'path', 'plan', 'future'],
    href: '/tools/career-roadmap',
  },
  {
    id: 'roi-calculator',
    title: 'College ROI Calculator',
    description: 'Calculate return on investment for education',
    category: 'tools',
    keywords: ['roi', 'college', 'education', 'investment', 'return'],
    href: '/tools/roi-calculator',
  },
  {
    id: 'interview-questions',
    title: 'Interview Questions',
    description: 'Practice common interview questions',
    category: 'tools',
    keywords: ['interview', 'questions', 'practice', 'hr', 'technical'],
    href: '/tools/interview-questions',
  },
  {
    id: 'dsa-quiz',
    title: 'DSA Quiz',
    description: 'Test your Data Structures and Algorithms knowledge',
    category: 'tools',
    keywords: ['dsa', 'quiz', 'data structures', 'algorithms', 'practice'],
    href: '/tools/dsa-quiz',
  },
  {
    id: 'gd-topics',
    title: 'GD Topics',
    description: 'Group Discussion topics for practice',
    category: 'tools',
    keywords: ['gd', 'group', 'discussion', 'topics', 'practice'],
    href: '/tools/gd-topics',
  },
  {
    id: 'pomodoro-timer',
    title: 'Pomodoro Timer',
    description: 'Focus timer using the Pomodoro technique',
    category: 'tools',
    keywords: ['pomodoro', 'timer', 'focus', 'productivity', 'study'],
    href: '/tools/pomodoro-timer',
  },
  {
    id: 'flashcards',
    title: 'Flashcards',
    description: 'Create and study with digital flashcards',
    category: 'tools',
    keywords: ['flashcards', 'study', 'learn', 'memory', 'cards'],
    href: '/tools/flashcards',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Generate secure random passwords',
    category: 'tools',
    keywords: ['password', 'generator', 'secure', 'random', 'security'],
    href: '/tools/password-generator',
  },
  {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    description: 'Create QR codes for any text or URL',
    category: 'tools',
    keywords: ['qr', 'code', 'generator', 'create', 'scan'],
    href: '/tools/qr-code-generator',
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Format and validate JSON data',
    category: 'tools',
    keywords: ['json', 'format', 'validate', 'beautify', 'minify'],
    href: '/tools/json-formatter',
  },
  {
    id: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, and sentences',
    category: 'tools',
    keywords: ['word', 'counter', 'characters', 'count', 'text'],
    href: '/tools/word-counter',
  },
  {
    id: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text between different cases',
    category: 'tools',
    keywords: ['case', 'converter', 'uppercase', 'lowercase', 'text'],
    href: '/tools/case-converter',
  },
  {
    id: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text',
    category: 'tools',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generate'],
    href: '/tools/lorem-ipsum-generator',
  },
  {
    id: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate your exact age',
    category: 'tools',
    keywords: ['age', 'calculator', 'birthday', 'date', 'years'],
    href: '/tools/age-calculator',
  },
  {
    id: 'date-calculator',
    title: 'Date Calculator',
    description: 'Calculate difference between dates',
    category: 'tools',
    keywords: ['date', 'calculator', 'difference', 'days', 'between'],
    href: '/tools/date-calculator',
  },
  {
    id: 'percentage-calculator',
    title: 'Percentage Calculator',
    description: 'Calculate percentages easily',
    category: 'tools',
    keywords: ['percentage', 'calculator', 'percent', 'calculate', 'math'],
    href: '/tools/percentage-calculator',
  },
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    description: 'Convert between different units',
    category: 'tools',
    keywords: ['unit', 'converter', 'convert', 'measurement', 'length'],
    href: '/tools/unit-converter',
  },
  {
    id: 'number-converter',
    title: 'Number Converter',
    description: 'Convert between number systems',
    category: 'tools',
    keywords: ['number', 'converter', 'binary', 'hex', 'decimal'],
    href: '/tools/number-converter',
  },
  {
    id: 'gpa-converter',
    title: 'GPA Converter',
    description: 'Convert GPA between different scales',
    category: 'tools',
    keywords: ['gpa', 'converter', 'grade', 'scale', '4.0'],
    href: '/tools/gpa-converter',
  },
  {
    id: 'marks-calculator',
    title: 'Marks Calculator',
    description: 'Calculate your marks and percentages',
    category: 'tools',
    keywords: ['marks', 'calculator', 'percentage', 'grade', 'score'],
    href: '/tools/marks-calculator',
  },
  {
    id: 'study-planner',
    title: 'Study Planner',
    description: 'Plan and organize your study schedule',
    category: 'tools',
    keywords: ['study', 'planner', 'schedule', 'plan', 'organize'],
    href: '/tools/study-planner',
  },
  {
    id: 'study-tracker',
    title: 'Study Tracker',
    description: 'Track your study progress',
    category: 'tools',
    keywords: ['study', 'tracker', 'progress', 'track', 'hours'],
    href: '/tools/study-tracker',
  },
  {
    id: 'study-hours-calculator',
    title: 'Study Hours Calculator',
    description: 'Calculate study hours needed',
    category: 'tools',
    keywords: ['study', 'hours', 'calculator', 'time', 'plan'],
    href: '/tools/study-hours-calculator',
  },
  {
    id: 'exam-countdown',
    title: 'Exam Countdown',
    description: 'Countdown timer for your exams',
    category: 'tools',
    keywords: ['exam', 'countdown', 'timer', 'days', 'left'],
    href: '/tools/exam-countdown',
  },
  {
    id: 'syllabus-tracker',
    title: 'Syllabus Tracker',
    description: 'Track your syllabus completion',
    category: 'tools',
    keywords: ['syllabus', 'tracker', 'progress', 'complete', 'subjects'],
    href: '/tools/syllabus-tracker',
  },
  {
    id: 'skills-assessment',
    title: 'Skills Assessment',
    description: 'Assess your skills and identify gaps',
    category: 'tools',
    keywords: ['skills', 'assessment', 'test', 'evaluate', 'gap'],
    href: '/tools/skills-assessment',
  },
  {
    id: 'skills-gap-analyzer',
    title: 'Skills Gap Analyzer',
    description: 'Analyze skill gaps for your target role',
    category: 'tools',
    keywords: ['skills', 'gap', 'analyzer', 'role', 'improve'],
    href: '/tools/skills-gap-analyzer',
  },
  {
    id: 'technical-quiz',
    title: 'Technical Quiz',
    description: 'Test your technical knowledge',
    category: 'tools',
    keywords: ['technical', 'quiz', 'test', 'coding', 'programming'],
    href: '/tools/technical-quiz',
  },
  {
    id: 'placement-readiness',
    title: 'Placement Readiness',
    description: 'Check if you are placement ready',
    category: 'tools',
    keywords: ['placement', 'readiness', 'test', 'job', 'ready'],
    href: '/tools/placement-readiness',
  },
  {
    id: 'interview-checklist',
    title: 'Interview Checklist',
    description: 'Checklist for interview preparation',
    category: 'tools',
    keywords: ['interview', 'checklist', 'prepare', 'list', 'ready'],
    href: '/tools/interview-checklist',
  },
  {
    id: 'application-tracker',
    title: 'Application Tracker',
    description: 'Track your job applications',
    category: 'tools',
    keywords: ['application', 'tracker', 'job', 'track', 'status'],
    href: '/tools/application-tracker',
  },
  {
    id: 'deadline-calculator',
    title: 'Deadline Calculator',
    description: 'Calculate days until deadlines',
    category: 'tools',
    keywords: ['deadline', 'calculator', 'days', 'date', 'countdown'],
    href: '/tools/deadline-calculator',
  },
  {
    id: 'checklist-generator',
    title: 'Checklist Generator',
    description: 'Generate custom checklists',
    category: 'tools',
    keywords: ['checklist', 'generator', 'create', 'list', 'tasks'],
    href: '/tools/checklist-generator',
  },
  {
    id: 'project-ideas',
    title: 'Project Ideas',
    description: 'Get project ideas for your resume',
    category: 'tools',
    keywords: ['project', 'ideas', 'resume', 'portfolio', 'build'],
    href: '/tools/project-ideas',
  },
  {
    id: 'github-readme-generator',
    title: 'GitHub README Generator',
    description: 'Generate README files for GitHub',
    category: 'tools',
    keywords: ['github', 'readme', 'generator', 'markdown', 'profile'],
    href: '/tools/github-readme-generator',
  },
  {
    id: 'linkedin-generator',
    title: 'LinkedIn Generator',
    description: 'Generate LinkedIn profile content',
    category: 'tools',
    keywords: ['linkedin', 'generator', 'profile', 'summary', 'headline'],
    href: '/tools/linkedin-generator',
  },
  {
    id: 'cold-email-generator',
    title: 'Cold Email Generator',
    description: 'Generate effective cold emails',
    category: 'tools',
    keywords: ['cold', 'email', 'generator', 'outreach', 'template'],
    href: '/tools/cold-email-generator',
  },
  {
    id: 'hr-templates',
    title: 'HR Templates',
    description: 'Templates for HR communication',
    category: 'tools',
    keywords: ['hr', 'templates', 'email', 'communication', 'letter'],
    href: '/tools/hr-templates',
  },
  {
    id: 'lor-sop-generator',
    title: 'LOR/SOP Generator',
    description: 'Generate Letters of Recommendation and SOPs',
    category: 'tools',
    keywords: ['lor', 'sop', 'letter', 'recommendation', 'statement'],
    href: '/tools/lor-sop-generator',
  },
  {
    id: 'sop-outliner',
    title: 'SOP Outliner',
    description: 'Outline your Statement of Purpose',
    category: 'tools',
    keywords: ['sop', 'outliner', 'statement', 'purpose', 'outline'],
    href: '/tools/sop-outliner',
  },
  {
    id: 'visa-timeline',
    title: 'Visa Timeline',
    description: 'Track visa application timeline',
    category: 'tools',
    keywords: ['visa', 'timeline', 'application', 'track', 'status'],
    href: '/tools/visa-timeline',
  },
  {
    id: 'scholarship-checker',
    title: 'Scholarship Checker',
    description: 'Check scholarship eligibility',
    category: 'tools',
    keywords: ['scholarship', 'checker', 'eligibility', 'check', 'financial'],
    href: '/tools/scholarship-checker',
  },
  {
    id: 'student-budget-planner',
    title: 'Student Budget Planner',
    description: 'Plan your student budget',
    category: 'tools',
    keywords: ['student', 'budget', 'planner', 'money', 'finance'],
    href: '/tools/student-budget-planner',
  },
  {
    id: 'salary-insights',
    title: 'Salary Insights',
    description: 'Get salary insights for different roles',
    category: 'tools',
    keywords: ['salary', 'insights', 'compensation', 'compare', 'industry'],
    href: '/tools/salary-insights',
  },
  {
    id: 'salary-bond-tracker',
    title: 'Salary Bond Tracker',
    description: 'Track salary bond obligations',
    category: 'tools',
    keywords: ['salary', 'bond', 'tracker', 'contract', 'agreement'],
    href: '/tools/salary-bond-tracker',
  },
  {
    id: 'ats-checker',
    title: 'ATS Checker',
    description: 'Check if your resume is ATS friendly',
    category: 'tools',
    keywords: ['ats', 'checker', 'resume', 'applicant', 'tracking'],
    href: '/tools/ats-checker',
  },
  {
    id: 'job-description-enhancer',
    title: 'Job Description Enhancer',
    description: 'Enhance job descriptions',
    category: 'tools',
    keywords: ['job', 'description', 'enhancer', 'improve', 'posting'],
    href: '/tools/job-description-enhancer',
  },
  {
    id: 'academic-calendar',
    title: 'Academic Calendar',
    description: 'View and manage academic calendar',
    category: 'tools',
    keywords: ['academic', 'calendar', 'semester', 'schedule', 'dates'],
    href: '/tools/academic-calendar',
  },
  {
    id: 'world-clock',
    title: 'World Clock',
    description: 'View time across different time zones',
    category: 'tools',
    keywords: ['world', 'clock', 'time', 'zone', 'timezone'],
    href: '/tools/world-clock',
  },
  {
    id: 'random-generator',
    title: 'Random Generator',
    description: 'Generate random numbers and strings',
    category: 'tools',
    keywords: ['random', 'generator', 'number', 'string', 'pick'],
    href: '/tools/random-generator',
  },
];

// Games data
const games: SearchItem[] = [
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Test your memory with card matching game',
    category: 'games',
    keywords: ['memory', 'match', 'cards', 'brain', 'puzzle'],
    href: '/games/memory-match',
  },
  {
    id: 'memory-matrix',
    title: 'Memory Matrix',
    description: 'Remember patterns in a grid',
    category: 'games',
    keywords: ['memory', 'matrix', 'grid', 'pattern', 'brain'],
    href: '/games/memory-matrix',
  },
  {
    id: 'speed-math',
    title: 'Speed Math',
    description: 'Quick math calculations challenge',
    category: 'games',
    keywords: ['speed', 'math', 'quick', 'calculate', 'arithmetic'],
    href: '/games/speed-math',
  },
  {
    id: 'mental-math',
    title: 'Mental Math',
    description: 'Mental arithmetic practice game',
    category: 'games',
    keywords: ['mental', 'math', 'arithmetic', 'calculate', 'numbers'],
    href: '/games/mental-math',
  },
  {
    id: 'math-speed-test',
    title: 'Math Speed Test',
    description: 'Test your math speed',
    category: 'games',
    keywords: ['math', 'speed', 'test', 'quick', 'numbers'],
    href: '/games/math-speed-test',
  },
  {
    id: 'number-sequence',
    title: 'Number Sequence',
    description: 'Find the next number in the sequence',
    category: 'games',
    keywords: ['number', 'sequence', 'pattern', 'logic', 'series'],
    href: '/games/number-sequence',
  },
  {
    id: 'number-series',
    title: 'Number Series',
    description: 'Complete the number series',
    category: 'games',
    keywords: ['number', 'series', 'pattern', 'sequence', 'logic'],
    href: '/games/number-series',
  },
  {
    id: 'pattern-recognition',
    title: 'Pattern Recognition',
    description: 'Identify patterns in images',
    category: 'games',
    keywords: ['pattern', 'recognition', 'visual', 'identify', 'logic'],
    href: '/games/pattern-recognition',
  },
  {
    id: 'pattern-finder',
    title: 'Pattern Finder',
    description: 'Find hidden patterns',
    category: 'games',
    keywords: ['pattern', 'finder', 'find', 'hidden', 'puzzle'],
    href: '/games/pattern-finder',
  },
  {
    id: 'logic-puzzle',
    title: 'Logic Puzzle',
    description: 'Solve logical reasoning puzzles',
    category: 'games',
    keywords: ['logic', 'puzzle', 'reasoning', 'solve', 'brain'],
    href: '/games/logic-puzzle',
  },
  {
    id: 'logic-builder',
    title: 'Logic Builder',
    description: 'Build logical solutions',
    category: 'games',
    keywords: ['logic', 'builder', 'build', 'solve', 'reasoning'],
    href: '/games/logic-builder',
  },
  {
    id: 'sudoku-trainer',
    title: 'Sudoku Trainer',
    description: 'Practice and master Sudoku',
    category: 'games',
    keywords: ['sudoku', 'trainer', 'numbers', 'puzzle', 'grid'],
    href: '/games/sudoku-trainer',
  },
  {
    id: 'word-scramble',
    title: 'Word Scramble',
    description: 'Unscramble words quickly',
    category: 'games',
    keywords: ['word', 'scramble', 'unscramble', 'letters', 'vocabulary'],
    href: '/games/word-scramble',
  },
  {
    id: 'word-association',
    title: 'Word Association',
    description: 'Connect words by association',
    category: 'games',
    keywords: ['word', 'association', 'connect', 'related', 'vocabulary'],
    href: '/games/word-association',
  },
  {
    id: 'spelling-bee',
    title: 'Spelling Bee',
    description: 'Test your spelling skills',
    category: 'games',
    keywords: ['spelling', 'bee', 'words', 'spell', 'vocabulary'],
    href: '/games/spelling-bee',
  },
  {
    id: 'synonym-match',
    title: 'Synonym Match',
    description: 'Match words with their synonyms',
    category: 'games',
    keywords: ['synonym', 'match', 'words', 'vocabulary', 'meaning'],
    href: '/games/synonym-match',
  },
  {
    id: 'antonym-challenge',
    title: 'Antonym Challenge',
    description: 'Find opposite words',
    category: 'games',
    keywords: ['antonym', 'challenge', 'opposite', 'words', 'vocabulary'],
    href: '/games/antonym-challenge',
  },
  {
    id: 'trivia-quiz',
    title: 'Trivia Quiz',
    description: 'Test your general knowledge',
    category: 'games',
    keywords: ['trivia', 'quiz', 'general', 'knowledge', 'questions'],
    href: '/games/trivia-quiz',
  },
  {
    id: 'daily-riddle',
    title: 'Daily Riddle',
    description: 'Solve a new riddle every day',
    category: 'games',
    keywords: ['daily', 'riddle', 'puzzle', 'solve', 'brain'],
    href: '/games/daily-riddle',
  },
  {
    id: 'think-fast',
    title: 'Think Fast',
    description: 'Quick thinking challenges',
    category: 'games',
    keywords: ['think', 'fast', 'quick', 'speed', 'reaction'],
    href: '/games/think-fast',
  },
  {
    id: 'reaction-time-test',
    title: 'Reaction Time Test',
    description: 'Test your reaction speed',
    category: 'games',
    keywords: ['reaction', 'time', 'test', 'speed', 'reflex'],
    href: '/games/reaction-time-test',
  },
  {
    id: 'quick-click-challenge',
    title: 'Quick Click Challenge',
    description: 'Click as fast as you can',
    category: 'games',
    keywords: ['quick', 'click', 'challenge', 'speed', 'mouse'],
    href: '/games/quick-click-challenge',
  },
  {
    id: 'attention-trainer',
    title: 'Attention Trainer',
    description: 'Improve your attention span',
    category: 'games',
    keywords: ['attention', 'trainer', 'focus', 'concentrate', 'brain'],
    href: '/games/attention-trainer',
  },
  {
    id: 'focus-booster',
    title: 'Focus Booster',
    description: 'Boost your focus and concentration',
    category: 'games',
    keywords: ['focus', 'booster', 'concentrate', 'attention', 'brain'],
    href: '/games/focus-booster',
  },
  {
    id: 'concentration-test',
    title: 'Concentration Test',
    description: 'Test your concentration level',
    category: 'games',
    keywords: ['concentration', 'test', 'focus', 'attention', 'brain'],
    href: '/games/concentration-test',
  },
  {
    id: 'concentration-challenge',
    title: 'Concentration Challenge',
    description: 'Challenge your concentration',
    category: 'games',
    keywords: ['concentration', 'challenge', 'focus', 'attention', 'brain'],
    href: '/games/concentration-challenge',
  },
  {
    id: 'speed-focus-game',
    title: 'Speed Focus Game',
    description: 'Balance speed and accuracy',
    category: 'games',
    keywords: ['speed', 'focus', 'game', 'accuracy', 'quick'],
    href: '/games/speed-focus-game',
  },
  {
    id: 'brain-logic-test',
    title: 'Brain Logic Test',
    description: 'Test your logical thinking',
    category: 'games',
    keywords: ['brain', 'logic', 'test', 'thinking', 'reasoning'],
    href: '/games/brain-logic-test',
  },
  {
    id: 'reasoning-master',
    title: 'Reasoning Master',
    description: 'Master logical reasoning',
    category: 'games',
    keywords: ['reasoning', 'master', 'logic', 'thinking', 'brain'],
    href: '/games/reasoning-master',
  },
  {
    id: 'critical-thinking-quiz',
    title: 'Critical Thinking Quiz',
    description: 'Test critical thinking skills',
    category: 'games',
    keywords: ['critical', 'thinking', 'quiz', 'reasoning', 'analysis'],
    href: '/games/critical-thinking-quiz',
  },
  {
    id: 'odd-one-out',
    title: 'Odd One Out',
    description: 'Find what doesnt belong',
    category: 'games',
    keywords: ['odd', 'one', 'out', 'different', 'find'],
    href: '/games/odd-one-out',
  },
  {
    id: 'sequence-solver',
    title: 'Sequence Solver',
    description: 'Solve sequence puzzles',
    category: 'games',
    keywords: ['sequence', 'solver', 'pattern', 'puzzle', 'logic'],
    href: '/games/sequence-solver',
  },
  {
    id: 'visual-logic-game',
    title: 'Visual Logic Game',
    description: 'Visual logical puzzles',
    category: 'games',
    keywords: ['visual', 'logic', 'game', 'puzzle', 'pattern'],
    href: '/games/visual-logic-game',
  },
  {
    id: 'card-flip-memory',
    title: 'Card Flip Memory',
    description: 'Classic card flipping memory game',
    category: 'games',
    keywords: ['card', 'flip', 'memory', 'match', 'game'],
    href: '/games/card-flip-memory',
  },
  {
    id: 'quick-recall',
    title: 'Quick Recall',
    description: 'Recall information quickly',
    category: 'games',
    keywords: ['quick', 'recall', 'memory', 'fast', 'remember'],
    href: '/games/quick-recall',
  },
  {
    id: 'mind-snapshot',
    title: 'Mind Snapshot',
    description: 'Remember visual snapshots',
    category: 'games',
    keywords: ['mind', 'snapshot', 'memory', 'visual', 'remember'],
    href: '/games/mind-snapshot',
  },
  {
    id: 'memory-power-test',
    title: 'Memory Power Test',
    description: 'Test your memory power',
    category: 'games',
    keywords: ['memory', 'power', 'test', 'brain', 'remember'],
    href: '/games/memory-power-test',
  },
  {
    id: 'debugging-challenge',
    title: 'Debugging Challenge',
    description: 'Find and fix code bugs',
    category: 'games',
    keywords: ['debugging', 'challenge', 'code', 'bug', 'fix'],
    href: '/games/debugging-challenge',
  },
  {
    id: 'predict-output',
    title: 'Predict Output',
    description: 'Predict code output',
    category: 'games',
    keywords: ['predict', 'output', 'code', 'result', 'programming'],
    href: '/games/predict-output',
  },
  {
    id: 'algorithm-thinking',
    title: 'Algorithm Thinking',
    description: 'Think through algorithms',
    category: 'games',
    keywords: ['algorithm', 'thinking', 'logic', 'steps', 'programming'],
    href: '/games/algorithm-thinking',
  },
  {
    id: 'complexity-cracker',
    title: 'Complexity Cracker',
    description: 'Understand time and space complexity',
    category: 'games',
    keywords: ['complexity', 'cracker', 'big-o', 'time', 'space'],
    href: '/games/complexity-cracker',
  },
  {
    id: 'error-spotter',
    title: 'Error Spotter',
    description: 'Spot errors in code',
    category: 'games',
    keywords: ['error', 'spotter', 'code', 'bug', 'find'],
    href: '/games/error-spotter',
  },
  {
    id: 'problem-decomposition',
    title: 'Problem Decomposition',
    description: 'Break down complex problems',
    category: 'games',
    keywords: ['problem', 'decomposition', 'break', 'solve', 'analyze'],
    href: '/games/problem-decomposition',
  },
  {
    id: 'constraint-crusher',
    title: 'Constraint Crusher',
    description: 'Solve constraint-based puzzles',
    category: 'games',
    keywords: ['constraint', 'crusher', 'puzzle', 'solve', 'logic'],
    href: '/games/constraint-crusher',
  },
  {
    id: 'percentage-puzzle',
    title: 'Percentage Puzzle',
    description: 'Solve percentage problems',
    category: 'games',
    keywords: ['percentage', 'puzzle', 'math', 'calculate', 'percent'],
    href: '/games/percentage-puzzle',
  },
  {
    id: 'profit-loss-game',
    title: 'Profit Loss Game',
    description: 'Calculate profit and loss',
    category: 'games',
    keywords: ['profit', 'loss', 'game', 'calculate', 'business'],
    href: '/games/profit-loss-game',
  },
  {
    id: 'time-work-challenge',
    title: 'Time Work Challenge',
    description: 'Solve time and work problems',
    category: 'games',
    keywords: ['time', 'work', 'challenge', 'math', 'aptitude'],
    href: '/games/time-work-challenge',
  },
  {
    id: 'situation-judgment',
    title: 'Situation Judgment',
    description: 'Make decisions in scenarios',
    category: 'games',
    keywords: ['situation', 'judgment', 'decision', 'scenario', 'test'],
    href: '/games/situation-judgment',
  },
  {
    id: 'email-etiquette',
    title: 'Email Etiquette',
    description: 'Learn professional email writing',
    category: 'games',
    keywords: ['email', 'etiquette', 'professional', 'write', 'communication'],
    href: '/games/email-etiquette',
  },
  {
    id: 'interview-ready',
    title: 'Interview Ready',
    description: 'Practice interview scenarios',
    category: 'games',
    keywords: ['interview', 'ready', 'practice', 'prepare', 'questions'],
    href: '/games/interview-ready',
  },
  {
    id: 'smart-choice',
    title: 'Smart Choice',
    description: 'Make smart decisions',
    category: 'games',
    keywords: ['smart', 'choice', 'decision', 'choose', 'think'],
    href: '/games/smart-choice',
  },
  {
    id: 'data-detective',
    title: 'Data Detective',
    description: 'Analyze and interpret data',
    category: 'games',
    keywords: ['data', 'detective', 'analyze', 'interpret', 'statistics'],
    href: '/games/data-detective',
  },
  {
    id: 'chart-challenge',
    title: 'Chart Challenge',
    description: 'Read and interpret charts',
    category: 'games',
    keywords: ['chart', 'challenge', 'graphs', 'interpret', 'data'],
    href: '/games/chart-challenge',
  },
  {
    id: 'stats-skeptic',
    title: 'Stats Skeptic',
    description: 'Question statistical claims',
    category: 'games',
    keywords: ['stats', 'skeptic', 'statistics', 'analyze', 'critical'],
    href: '/games/stats-skeptic',
  },
  {
    id: 'fallacy-detective',
    title: 'Fallacy Detective',
    description: 'Spot logical fallacies',
    category: 'games',
    keywords: ['fallacy', 'detective', 'logic', 'argument', 'reasoning'],
    href: '/games/fallacy-detective',
  },
  {
    id: 'bias-buster',
    title: 'Bias Buster',
    description: 'Identify cognitive biases',
    category: 'games',
    keywords: ['bias', 'buster', 'cognitive', 'identify', 'thinking'],
    href: '/games/bias-buster',
  },
  {
    id: 'risk-radar',
    title: 'Risk Radar',
    description: 'Assess and manage risks',
    category: 'games',
    keywords: ['risk', 'radar', 'assess', 'manage', 'analyze'],
    href: '/games/risk-radar',
  },
  {
    id: 'strategic-standoff',
    title: 'Strategic Standoff',
    description: 'Strategic thinking challenges',
    category: 'games',
    keywords: ['strategic', 'standoff', 'strategy', 'think', 'plan'],
    href: '/games/strategic-standoff',
  },
  {
    id: 'decision-matrix-lab',
    title: 'Decision Matrix Lab',
    description: 'Use decision matrices',
    category: 'games',
    keywords: ['decision', 'matrix', 'lab', 'analyze', 'choose'],
    href: '/games/decision-matrix-lab',
  },
  {
    id: 'fermi-estimation-duel',
    title: 'Fermi Estimation Duel',
    description: 'Practice Fermi estimation',
    category: 'games',
    keywords: ['fermi', 'estimation', 'duel', 'estimate', 'logic'],
    href: '/games/fermi-estimation-duel',
  },
  {
    id: 'causal-chain-builder',
    title: 'Causal Chain Builder',
    description: 'Build cause and effect chains',
    category: 'games',
    keywords: ['causal', 'chain', 'builder', 'cause', 'effect'],
    href: '/games/causal-chain-builder',
  },
  {
    id: 'concept-sprint',
    title: 'Concept Sprint',
    description: 'Quick concept learning',
    category: 'games',
    keywords: ['concept', 'sprint', 'quick', 'learn', 'idea'],
    href: '/games/concept-sprint',
  },
  {
    id: 'deep-problem-marathon',
    title: 'Deep Problem Marathon',
    description: 'Solve complex problems',
    category: 'games',
    keywords: ['deep', 'problem', 'marathon', 'complex', 'solve'],
    href: '/games/deep-problem-marathon',
  },
  {
    id: 'system-simulator',
    title: 'System Simulator',
    description: 'Simulate systems thinking',
    category: 'games',
    keywords: ['system', 'simulator', 'simulate', 'think', 'model'],
    href: '/games/system-simulator',
  },
  {
    id: 'math-proof-builder',
    title: 'Math Proof Builder',
    description: 'Build mathematical proofs',
    category: 'games',
    keywords: ['math', 'proof', 'builder', 'logic', 'theorem'],
    href: '/games/math-proof-builder',
  },
  {
    id: 'derivation-race',
    title: 'Derivation Race',
    description: 'Race through derivations',
    category: 'games',
    keywords: ['derivation', 'race', 'math', 'calculus', 'formula'],
    href: '/games/derivation-race',
  },
  {
    id: 'dimensional-detective',
    title: 'Dimensional Detective',
    description: 'Solve dimensional analysis',
    category: 'games',
    keywords: ['dimensional', 'detective', 'analysis', 'physics', 'units'],
    href: '/games/dimensional-detective',
  },
  {
    id: 'physics-intuition-lab',
    title: 'Physics Intuition Lab',
    description: 'Develop physics intuition',
    category: 'games',
    keywords: ['physics', 'intuition', 'lab', 'science', 'experiment'],
    href: '/games/physics-intuition-lab',
  },
  {
    id: 'reaction-mechanism',
    title: 'Reaction Mechanism',
    description: 'Learn chemical reactions',
    category: 'games',
    keywords: ['reaction', 'mechanism', 'chemistry', 'organic', 'science'],
    href: '/games/reaction-mechanism',
  },
  {
    id: 'organic-synthesis',
    title: 'Organic Synthesis',
    description: 'Plan organic syntheses',
    category: 'games',
    keywords: ['organic', 'synthesis', 'chemistry', 'reaction', 'compound'],
    href: '/games/organic-synthesis',
  },
  {
    id: 'biology-pathway',
    title: 'Biology Pathway',
    description: 'Learn biological pathways',
    category: 'games',
    keywords: ['biology', 'pathway', 'science', 'cell', 'process'],
    href: '/games/biology-pathway',
  },
  {
    id: 'clinical-case',
    title: 'Clinical Case',
    description: 'Solve clinical case studies',
    category: 'games',
    keywords: ['clinical', 'case', 'medical', 'diagnose', 'study'],
    href: '/games/clinical-case',
  },
  // Coding games
  {
    id: 'code-battle',
    title: 'Code Battle',
    description: 'Competitive coding challenges',
    category: 'games',
    keywords: ['code', 'battle', 'competitive', 'coding', 'challenge'],
    href: '/games/coding/code-battle',
  },
  {
    id: 'debug-arena',
    title: 'Debug Arena',
    description: 'Debug code in the arena',
    category: 'games',
    keywords: ['debug', 'arena', 'code', 'fix', 'bug'],
    href: '/games/coding/debug-arena',
  },
  {
    id: 'algorithm-builder',
    title: 'Algorithm Builder',
    description: 'Build algorithms step by step',
    category: 'games',
    keywords: ['algorithm', 'builder', 'code', 'logic', 'step'],
    href: '/games/coding/algorithm-builder',
  },
  {
    id: 'output-prediction',
    title: 'Output Prediction',
    description: 'Predict code output accurately',
    category: 'games',
    keywords: ['output', 'prediction', 'code', 'result', 'guess'],
    href: '/games/coding/output-prediction',
  },
];

// Pages data
const pages: SearchItem[] = [
  {
    id: 'home',
    title: 'Home',
    description: 'Sproutern home page',
    category: 'pages',
    keywords: ['home', 'main', 'landing'],
    href: '/',
  },
  {
    id: 'about',
    title: 'About Us',
    description: 'Learn about Sproutern and our mission',
    category: 'pages',
    keywords: ['about', 'team', 'mission', 'company'],
    href: '/about',
  },
  {
    id: 'contact',
    title: 'Contact',
    description: 'Get in touch with us',
    category: 'pages',
    keywords: ['contact', 'reach', 'email', 'support'],
    href: '/contact',
  },
  {
    id: 'companies',
    title: 'Companies',
    description: 'Explore companies and their profiles',
    category: 'pages',
    keywords: ['companies', 'employers', 'organizations', 'firms'],
    href: '/companies',
  },
  {
    id: 'scholarships',
    title: 'Scholarships',
    description: 'Find scholarships and financial aid',
    category: 'pages',
    keywords: ['scholarships', 'financial', 'aid', 'funding', 'grants'],
    href: '/scholarships',
  },
  {
    id: 'resources',
    title: 'Resources',
    description: 'Career resources and guides',
    category: 'pages',
    keywords: ['resources', 'guides', 'materials', 'help'],
    href: '/resources',
  },
  {
    id: 'blog',
    title: 'Blog',
    description: 'Read career advice and industry insights',
    category: 'pages',
    keywords: ['blog', 'articles', 'posts', 'news'],
    href: '/blog',
  },
  {
    id: 'interview-experiences',
    title: 'Interview Experiences',
    description: 'Read real interview experiences',
    category: 'pages',
    keywords: ['interview', 'experiences', 'stories', 'preparation'],
    href: '/interview-experiences',
  },
  {
    id: 'tools',
    title: 'Tools',
    description: 'Career and productivity tools',
    category: 'pages',
    keywords: ['tools', 'utilities', 'calculators', 'generators'],
    href: '/tools',
  },
  {
    id: 'games',
    title: 'Games',
    description: 'Brain training and learning games',
    category: 'pages',
    keywords: ['games', 'play', 'brain', 'training'],
    href: '/games',
  },
  {
    id: 'countries',
    title: 'Countries',
    description: 'Explore opportunities by country',
    category: 'pages',
    keywords: ['countries', 'international', 'global', 'abroad'],
    href: '/countries',
  },
  {
    id: 'school',
    title: 'School',
    description: 'Resources for school students',
    category: 'pages',
    keywords: ['school', 'students', 'education', 'learning'],
    href: '/school',
  },
  {
    id: 'college',
    title: 'College',
    description: 'Resources for college students',
    category: 'pages',
    keywords: ['college', 'university', 'students', 'campus'],
    href: '/college',
  },
  {
    id: 'freshers',
    title: 'Freshers',
    description: 'Resources for fresh graduates',
    category: 'pages',
    keywords: ['freshers', 'graduates', 'entry-level', 'first-job'],
    href: '/freshers',
  },
  {
    id: 'faq',
    title: 'FAQ',
    description: 'Frequently asked questions',
    category: 'pages',
    keywords: ['faq', 'questions', 'answers', 'help'],
    href: '/faq',
  },
  {
    id: 'founder',
    title: 'Our Founder',
    description: 'Learn about our founder',
    category: 'pages',
    keywords: ['founder', 'ceo', 'creator', 'leader'],
    href: '/founder',
  },
  {
    id: 'privacy-policy',
    title: 'Privacy Policy',
    description: 'Our privacy policy',
    category: 'pages',
    keywords: ['privacy', 'policy', 'data', 'protection'],
    href: '/privacy-policy',
  },
  {
    id: 'terms-and-conditions',
    title: 'Terms and Conditions',
    description: 'Terms of service',
    category: 'pages',
    keywords: ['terms', 'conditions', 'service', 'agreement'],
    href: '/terms-and-conditions',
  },
  {
    id: 'roadmaps',
    title: 'Career Roadmaps',
    description: 'Career path roadmaps',
    category: 'pages',
    keywords: ['roadmaps', 'career', 'path', 'plan'],
    href: '/roadmaps',
  },
  {
    id: 'donate',
    title: 'Support Us',
    description: 'Donate to support Sproutern',
    category: 'pages',
    keywords: ['donate', 'support', 'contribute', 'help'],
    href: '/donate',
  },
  {
    id: 'testimonials',
    title: 'Testimonials',
    description: 'Success stories and reviews',
    category: 'pages',
    keywords: ['testimonials', 'reviews', 'success', 'stories'],
    href: '/testimonials',
  },
  {
    id: 'success-stories',
    title: 'Success Stories',
    description: 'Read success stories from users',
    category: 'pages',
    keywords: ['success', 'stories', 'achievements', 'wins'],
    href: '/success-stories',
  },
];

// Resources data
const resources: SearchItem[] = [
  {
    id: 'resume-guide',
    title: 'Resume Guide',
    description: 'Complete guide to writing a perfect resume',
    category: 'resources',
    keywords: ['resume', 'guide', 'write', 'cv', 'tips'],
    href: '/resources/resume-guide',
  },
  {
    id: 'resume-templates',
    title: 'Resume Templates',
    description: 'Professional resume templates',
    category: 'resources',
    keywords: ['resume', 'templates', 'download', 'format', 'sample'],
    href: '/resources/resume-templates',
  },
  {
    id: 'interview-prep',
    title: 'Interview Preparation',
    description: 'Comprehensive interview preparation guide',
    category: 'resources',
    keywords: ['interview', 'preparation', 'questions', 'answers', 'hr'],
    href: '/resources/interview-prep',
  },
  {
    id: 'interview-cheatsheet',
    title: 'Interview Cheatsheet',
    description: 'Quick reference for interview preparation',
    category: 'resources',
    keywords: ['interview', 'cheatsheet', 'quick', 'reference', 'tips'],
    href: '/resources/interview-cheatsheet',
  },
  {
    id: 'aptitude-formulas',
    title: 'Aptitude Formulas',
    description: 'All aptitude formulas in one place',
    category: 'resources',
    keywords: ['aptitude', 'formulas', 'math', 'shortcuts', 'quick'],
    href: '/resources/aptitude-formulas',
  },
  {
    id: 'cover-letters',
    title: 'Cover Letter Templates',
    description: 'Professional cover letter templates',
    category: 'resources',
    keywords: ['cover', 'letter', 'templates', 'sample', 'format'],
    href: '/resources/cover-letters',
  },
  {
    id: 'career-planning',
    title: 'Career Planning',
    description: 'Career planning guide and resources',
    category: 'resources',
    keywords: ['career', 'planning', 'roadmap', 'goals', 'strategy'],
    href: '/resources/career-planning',
  },
  {
    id: 'skill-development',
    title: 'Skill Development',
    description: 'Learn in-demand technical and soft skills',
    category: 'resources',
    keywords: ['skills', 'development', 'upskilling', 'learning', 'career'],
    href: '/resources/skill-development',
  },
  {
    id: 'email-templates',
    title: 'Email Templates',
    description: 'Professional email templates for students and job seekers',
    category: 'resources',
    keywords: ['email', 'templates', 'follow-up', 'outreach', 'job application'],
    href: '/resources/email-templates',
  },
  {
    id: 'portfolio-templates',
    title: 'Portfolio Templates',
    description: 'Portfolio templates for developers, designers, and students',
    category: 'resources',
    keywords: ['portfolio', 'templates', 'projects', 'website', 'showcase'],
    href: '/resources/portfolio-templates',
  },
  {
    id: 'downloads',
    title: 'Downloadable Resources',
    description: 'Free downloadable career resources',
    category: 'resources',
    keywords: ['downloads', 'resources', 'pdf', 'templates', 'guides'],
    href: '/resources/downloads',
  },
  {
    id: 'salary-negotiation',
    title: 'Salary Negotiation Guide',
    description: 'How to negotiate your salary',
    category: 'resources',
    keywords: ['salary', 'negotiation', 'guide', 'tips', 'offer'],
    href: '/resources/salary-negotiation',
  },
  {
    id: 'linkedin-optimization',
    title: 'LinkedIn Optimization',
    description: 'Optimize your LinkedIn profile',
    category: 'resources',
    keywords: ['linkedin', 'optimization', 'profile', 'tips', 'networking'],
    href: '/resources/linkedin-optimization',
  },
  {
    id: 'networking-guide',
    title: 'Networking Guide',
    description: 'Build your professional network',
    category: 'resources',
    keywords: ['networking', 'guide', 'connections', 'professional', 'tips'],
    href: '/resources/networking',
  },
  {
    id: 'industry-insights',
    title: 'Industry Insights',
    description: 'Industry trends, benchmarks, and hiring insights',
    category: 'resources',
    keywords: ['industry', 'insights', 'salary', 'trends', 'hiring'],
    href: '/resources/industry-insights',
  },
  {
    id: 'github-profile',
    title: 'GitHub Profile Guide',
    description: 'Improve your GitHub profile and pinned repositories',
    category: 'resources',
    keywords: ['github', 'profile', 'readme', 'repositories', 'projects'],
    href: '/resources/github-profile',
  },
  {
    id: 'ats-resume-keywords',
    title: 'ATS Resume Keywords Guide',
    description: 'Match resume keywords to job descriptions',
    category: 'resources',
    keywords: ['ats', 'resume', 'keywords', 'job description', 'resume tips'],
    href: '/resources/ats-resume-keywords',
  },
];

// Generate blog items from blogPosts
const blogItems: SearchItem[] = blogPosts.map((post) => ({
  id: post.slug,
  title: post.title,
  description: post.excerpt,
  category: 'blog' as const,
  keywords: [
    post.category.toLowerCase(),
    ...post.title
      .toLowerCase()
      .split(' ')
      .filter((w) => w.length > 3),
    'blog',
    'article',
    'post',
  ],
  href: `/blog/${post.slug}`,
}));

// Interview experiences data (sample - you can expand this)
const interviewExperiences: SearchItem[] = [
  {
    id: 'bank-of-america',
    title: 'Bank of America Interview',
    description:
      'Interview experience at Bank of America for Software Developer role',
    category: 'interview-experiences',
    keywords: ['bank', 'america', 'boa', 'software', 'developer', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'optum',
    title: 'Optum Interview',
    description: 'Interview experience at Optum for Software Engineer role',
    category: 'interview-experiences',
    keywords: ['optum', 'healthcare', 'software', 'engineer', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'barclays',
    title: 'Barclays Interview',
    description: 'Interview experience at Barclays for Software Engineer role',
    category: 'interview-experiences',
    keywords: ['barclays', 'bank', 'software', 'engineer', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'societe-generale',
    title: 'Societe Generale Interview',
    description:
      'Interview experience at Societe Generale for Software Engineer role',
    category: 'interview-experiences',
    keywords: [
      'societe',
      'generale',
      'bank',
      'software',
      'engineer',
      'interview',
    ],
    href: '/interview-experiences',
  },
  {
    id: 'nortonlifelock',
    title: 'NortonLifeLock Interview',
    description:
      'Interview experience at NortonLifeLock for Software Engineer role',
    category: 'interview-experiences',
    keywords: [
      'norton',
      'lifelock',
      'security',
      'software',
      'engineer',
      'interview',
    ],
    href: '/interview-experiences',
  },
  {
    id: 'trimble',
    title: 'Trimble Interview',
    description: 'Interview experience at Trimble for Software Engineer role',
    category: 'interview-experiences',
    keywords: ['trimble', 'software', 'engineer', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'citi',
    title: 'Citi Interview',
    description: 'Interview experience at Citi for Software Engineer role',
    category: 'interview-experiences',
    keywords: ['citi', 'bank', 'software', 'engineer', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'tcs',
    title: 'TCS Interview',
    description: 'Interview experience at TCS for various roles',
    category: 'interview-experiences',
    keywords: ['tcs', 'tata', 'consultancy', 'mnc', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'infosys',
    title: 'Infosys Interview',
    description: 'Interview experience at Infosys for various roles',
    category: 'interview-experiences',
    keywords: ['infosys', 'mnc', 'it', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'wipro',
    title: 'Wipro Interview',
    description: 'Interview experience at Wipro for various roles',
    category: 'interview-experiences',
    keywords: ['wipro', 'mnc', 'it', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'cognizant',
    title: 'Cognizant Interview',
    description: 'Interview experience at Cognizant for various roles',
    category: 'interview-experiences',
    keywords: ['cognizant', 'cts', 'mnc', 'it', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'accenture',
    title: 'Accenture Interview',
    description: 'Interview experience at Accenture for various roles',
    category: 'interview-experiences',
    keywords: ['accenture', 'mnc', 'consulting', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'capgemini',
    title: 'Capgemini Interview',
    description: 'Interview experience at Capgemini for various roles',
    category: 'interview-experiences',
    keywords: ['capgemini', 'mnc', 'it', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'microsoft',
    title: 'Microsoft Interview',
    description: 'Interview experience at Microsoft for various roles',
    category: 'interview-experiences',
    keywords: ['microsoft', 'big tech', 'product', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'google',
    title: 'Google Interview',
    description: 'Interview experience at Google for various roles',
    category: 'interview-experiences',
    keywords: ['google', 'big tech', 'product', 'interview'],
    href: '/interview-experiences',
  },
  {
    id: 'amazon',
    title: 'Amazon Interview',
    description: 'Interview experience at Amazon for various roles',
    category: 'interview-experiences',
    keywords: ['amazon', 'big tech', 'product', 'interview'],
    href: '/interview-experiences',
  },
];

// Combine all search items
export const searchIndex: SearchItem[] = [
  ...tools,
  ...games,
  ...pages,
  ...resources,
  ...blogItems,
  ...interviewExperiences,
];

// Export individual arrays for filtering
export { tools, games, pages, resources, blogItems, interviewExperiences };
