# These are supported funding model platforms

github: itsPremkumar
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift subscription
# custom: ['https://sproutern.dpdns.org/donate']
