import {
  getPageSchema,
  generateJsonLdSchema,
} from '@/lib/seo/apply-complete-seo';
import { GitHubReadmeGenerator } from '@/components/tools/GitHubReadmeGenerator';
import { Github, Code, Terminal, Sparkles } from 'lucide-react';
import { ToolSEOContent } from '@/components/seo/ToolSEOContent';
import { toolsSEOContent } from '@/lib/seo/tool-seo-content';

export const metadata = {
  title: 'Free AI GitHub Profile README Generator',
  description:
    'Create a stunning GitHub profile README in seconds. Add stats, skills, dynamic badges, and more with our AI-powered generator.',
};

export default function GitHubReadmePage() {
  const schemas = getPageSchema('home');
  const content = toolsSEOContent['github-readme-generator'];

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={generateJsonLdSchema(schemas)}
      />
      <div className="container py-12">
        <div className="mx-auto max-w-6xl">
          {/* Header */}
          <div className="mb-12 text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-2 text-sm font-semibold text-primary">
              <Github className="h-4 w-4" />
              For Developers
            </div>
            <h1 className="mb-4 text-4xl font-bold md:text-5xl">
              AI GitHub Profile README Generator
            </h1>
            <p className="mx-auto max-w-2xl text-xl text-muted-foreground">
              Your profile is your resume. Make it stand out with dynamic stats,
              skill badges, and a professional bio generated by AI.
            </p>
          </div>

          {/* Features */}
          <div className="mb-10 grid grid-cols-2 gap-4 md:grid-cols-4">
            <div className="flex items-center gap-2 rounded-lg bg-gray-100 p-3 dark:bg-gray-800">
              <Terminal className="h-5 w-5" />
              <span className="text-sm font-medium">Markdown Ready</span>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-blue-50 p-3 dark:bg-blue-950">
              <Code className="h-5 w-5 text-blue-600" />
              <span className="text-sm font-medium">Skill Badges</span>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-green-50 p-3 dark:bg-green-950">
              <Github className="h-5 w-5 text-green-600" />
              <span className="text-sm font-medium">Live Stats</span>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-purple-50 p-3 dark:bg-purple-950">
              <Sparkles className="h-5 w-5 text-purple-600" />
              <span className="text-sm font-medium">AI Bio</span>
            </div>
          </div>

          <GitHubReadmeGenerator />

          {content && (
            <div className="mt-20">
              <ToolSEOContent
                toolSlug="github-readme-generator"
                enhancedContent={content}
              />
            </div>
          )}
        </div>
      </div>
    </>
  );
}
