blank_issues_enabled: true
contact_links:
  - name: Sproutern Documentation
    url: https://github.com/itsPremkumar/sproutern-oss/tree/main/docs
    about: Check the documentation first
  - name: GitHub Discussions
    url: https://github.com/itsPremkumar/sproutern-oss/discussions
    about: Ask questions and discuss ideas
